# Generated by Django 4.1.3 on 2022-11-21 09:11

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('self_clothes', '0002_alter_category_options_alter_self_clothes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='self_clothes',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=255),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=models.SET('Unknown'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
