# Generated by Django 4.1.3 on 2022-11-21 10:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('self_clothes', '0003_alter_self_clothes_description_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='clothes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='self_clothes.self_clothes'),
        ),
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Worse'), (2, 'Bad'), (3, 'Good'), (4, 'Excellent'), (5, 'Best')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='self_clothes',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
