# Generated by Django 4.1.3 on 2022-11-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_clothes', '0004_review_clothes_review_rate_review_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='self_clothes',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
